## Save to .config/starship.toml


# JavaCafe01 Prompt

format = "$all"
add_newline = true

[character]
error_symbol = "[ðŸ’€](bold red)"
success_symbol = "[ðŸ’€](bold green)"
vicmd_symbol = "[ðŸ’€](bold yellow)"
format = "$symbol [â‹Ÿ](bold bright-black) "

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[directory]
disabled = true

[line_break]
disabled = true

[lua]
symbol = "[î˜ ](blue) "
